[[constraint]]
  name = "github.com/akamensky/argparse"
  version = "1.2.1"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.1.31"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.6.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.3.0"

[prune]
  go-tests = true
  unused-packages = true
